name: morton_env
channels:
  - pytorch
  - conda-forge
  - clinicalgraphics
dependencies:
  - python=3.6
  - pytorch=0.4.1
  - torchvision=0.2.1
  - matplotlib=2.2.2
  - h5py=2.8.0
  - pandas=0.23.4
  - scikit-learn=0.20.0
  - tqdm=4.26.0
  - vtk=8.1.1
  - pip:
    - tensorflow-gpu==1.12.0
    - tensorboardX